/*
	This class is autogenerated by BuildOpenCVProxy. 
*/
using System;

namespace OpenCVProxy.Interop
{
    public static partial class Cv
    {
		public const int CV_RETR_EXTERNAL = 0;
		public const int CV_RETR_LIST = 1;
		public const int CV_RETR_CCOMP = 2;
		public const int CV_RETR_TREE = 3;
		public const int CV_CHAIN_CODE = 0;
		public const int CV_CHAIN_APPROX_NONE = 1;
		public const int CV_CHAIN_APPROX_SIMPLE = 2;
		public const int CV_CHAIN_APPROX_TC89_L1 = 3;
		public const int CV_CHAIN_APPROX_TC89_KCOS = 4;
		public const int CV_LINK_RUNS = 5;
		public const int CV_HAAR_MAGIC_VAL = 0x42500000;
		public const int CV_HAAR_FEATURE_MAX = 3;
	}
}
