/*
	This class is autogenerated by BuildOpenCVProxy. 
*/
using System;

namespace OpenCVProxy.Interop
{
    public static partial class CxCore
    {
		public const int IPL_DEPTH_SIGN = unchecked((int)0x80000000);
		public const int IPL_DEPTH_1U = 1;
		public const int IPL_DEPTH_8U = 8;
		public const int IPL_DEPTH_16U = 16;
		public const int IPL_DEPTH_32F = 32;
		public const int IPL_DATA_ORDER_PIXEL = 0;
		public const int IPL_DATA_ORDER_PLANE = 1;
		public const int IPL_ORIGIN_TL = 0;
		public const int IPL_ORIGIN_BL = 1;
		public const int IPL_ALIGN_4BYTES = 4;
		public const int IPL_ALIGN_8BYTES = 8;
		public const int IPL_ALIGN_16BYTES = 16;
		public const int IPL_ALIGN_32BYTES = 32;
		public const int IPL_BORDER_CONSTANT = 0;
		public const int IPL_BORDER_REPLICATE = 1;
		public const int IPL_BORDER_REFLECT = 2;
		public const int IPL_BORDER_WRAP = 3;
		public const int IPL_IMAGE_HEADER = 1;
		public const int IPL_IMAGE_DATA = 2;
		public const int IPL_IMAGE_ROI = 4;
		public const int IPL_BORDER_REFLECT_101 = 4;
		public const int IPL_DEPTH_64F = 64;
		public const int CV_CN_MAX = 64;
		public const int CV_CN_SHIFT = 3;
		public const int CV_8U = 0;
		public const int CV_8S = 1;
		public const int CV_16U = 2;
		public const int CV_16S = 3;
		public const int CV_32S = 4;
		public const int CV_32F = 5;
		public const int CV_64F = 6;
		public const int CV_USRTYPE1 = 7;
		public const int CV_MAT_CONT_FLAG_SHIFT = 14;
		public const int CV_MAT_TEMP_FLAG_SHIFT = 15;
		public const int CV_MAGIC_MASK = unchecked((int)0xFFFF0000);
		public const int CV_MAT_MAGIC_VAL = 0x42420000;
		public const int CV_MATND_MAGIC_VAL = 0x42430000;
		public const int CV_MAX_DIM = 32;
		public const int CV_SPARSE_MAT_MAGIC_VAL = 0x42440000;
		public const int CV_HIST_MAGIC_VAL = 0x42450000;
		public const int CV_HIST_ARRAY = 0;
		public const int CV_HIST_SPARSE = 1;
		public const int CV_HIST_UNIFORM = 1;
		public const int CV_TERMCRIT_ITER = 1;
		public const int CV_TERMCRIT_EPS = 2;
		public const int CV_STORAGE_MAGIC_VAL = 0x42890000;
		public const int CV_SEQ_MAGIC_VAL = 0x42990000;
		public const int CV_SET_MAGIC_VAL = 0x42980000;
		public const int CV_SEQ_ELTYPE_BITS = 9;
		public const int CV_SEQ_ELTYPE_GENERIC = 0;
		public const int CV_SEQ_KIND_BITS = 3;
		public const int CV_STORAGE_READ = 0;
		public const int CV_STORAGE_WRITE = 1;
		public const int CV_STORAGE_APPEND = 2;
		public const int CV_NODE_NONE = 0;
		public const int CV_NODE_INT = 1;
		public const int CV_NODE_REAL = 2;
		public const int CV_NODE_STR = 3;
		public const int CV_NODE_SEQ = 5;
		public const int CV_NODE_MAP = 6;
		public const int CV_NODE_TYPE_MASK = 7;
		public const int CV_NODE_USER = 16;
		public const int CV_NODE_EMPTY = 32;
		public const int CV_NODE_NAMED = 64;
		public const int CV_NODE_SEQ_SIMPLE = 256;
	}
}
